[target.aarch64-linux-android]
ar = "/opt/android-sdk/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android23-ar"
linker = "/opt/android-sdk/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android23-clang"

[target.armv7-linux-androideabi]
ar = "/opt/android-ndk/arm/bin/arm-linux-androideabi-ar"
linker = "/opt/android-ndk/arm/bin/arm-linux-androideabi-clang"

[target.x86_64-linux-android]
ar = "/opt/android-ndk/x86/bin/x86_64-linux-android-ar"
linker = "/opt/android-ndk/x86/bin/x86_64-linux-android-clang"
